fixed a bug that caused some file exports to not function
fixed a bug that caused some file exports to not function
I was using ARCtool to take a character model from a scene and convert it into an .arc file, trying to export in blender always fails with this error:
"Report: Error

Python: Traceback (most recent call last):
File "C:\Users\[REDACTED}\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\albam_reloaded\blender.py", line 410, in execute
func(obj, self.filepath)
File "C:\Users\[REDACTED}\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\albam_reloaded\engines\mtframework\blender_export.py", line 127, in export_arc
with open(destination_path, 'wb') as w:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\[REDACTED}\AppData\Local\Temp\tmpc3g4ywte\pawn\em\em85\model\missing texture.tex'

location: <unknown location>:-1"


This issue arises because Albam was trying to write missing texture.tex to a directory (pawn\em\em80\model\) that the temporary folder didn't have (since open() with 'wb' can't create missing parent directories automatically).